Repository Tribe-BTC/tribe-master, pull requests merged in 2023-10, with the labels that each got.

#8 Update LICENSE
  LICENSE
  README.md
Labels: documentation, enhancement

#9 Add proposal
  src/services/tribe.ts
Labels: enhancement, help wanted

#12 Delete CNAME
  CNAME
Labels: documentation

#14 Revert "Delete CNAME"
  CNAME
Labels: bug, documentation, enhancement

#13 Add Import modules for Proposal
  src/services/tribe.ts
Labels: enhancement, help wanted

#10 create proposals
  README.md
  src/app/shared/create-proposals.tsx
  src/app/shared/proposals.tsx
  src/app/shared/vote.tsx
  src/components/create-proposal/create-proposal-form.tsx
  src/components/create-tribe/create-tribe-form-tr.tsx
  src/components/create-tribe/index.tsx
  src/components/members/members-list.tsx
  src/components/screens/view-tribe-screen.tsx
  src/components/view-tribe/view-tribe.tsx
  src/components/vote/vote-details/vote-details-card.tsx
  src/components/vote/vote-list.tsx
  src/hooks/useMember.ts
  src/hooks/useProposal.ts
  src/hooks/useWithBitpac.ts
  src/layouts/sidebar/_menu-items.tsx
  src/utils/proposal-create/getInputs.ts
  src/utils/proposal-create/getOutputs.ts
  src/utils/proposal-create/getThreeFeeRates.ts
  src/utils/proposal-create/getTxSize.ts
  src/utils/proposal-create/spendCoints.ts
  src/utils/proposal/calculateVotePercentages.ts
  src/utils/proposal/checkTx.ts
  src/utils/proposal/checkUtxosInputs.ts
  src/utils/proposal/createTransaction.ts
  src/utils/proposal/fetchProposals.ts
  src/utils/proposal/fetchProposalsAndVotes.ts
  src/utils/proposal/fetchVotes.ts
  src/utils/proposal/getChange.ts
  src/utils/proposal/getOutputActions.ts
  src/utils/proposal/getProposal.ts
  src/utils/proposal/getProposalContent.ts
  src/utils/proposal/getProposalStatus.ts
  src/utils/proposal/getSignatures.ts
  src/utils/proposal/getVoteCounts.ts
  src/utils/proposal/getVoters.ts
  src/utils/utils.ts
Labels: documentation, enhancement

#34 Update Roadmap
  README.md
Labels: documentation, enhancement

#37 Upgrade roadmap
  README.md
Labels: documentation

#43 Add Xverse and more for Roadmap
  README.md
Labels: documentation

#48 Update new logos and sidebar bg color
  src/assets/images/tribeLogo-orange.png
  src/assets/images/tribeLogo-white.png
  src/assets/images/tribeTextLogo-black.png
  src/assets/images/tribeTextLogo-orange.png
  src/assets/images/tribeTextLogo-white.png
  src/components/ui/author-card.tsx
  src/components/ui/logo-icon.tsx
  src/components/ui/logo.tsx
  src/components/ui/menu-icon.tsx
  src/layouts/sidebar/_default.tsx
Labels: enhancement

#41 add required validation for inputs at create tribe and create proposals
  src/components/create-proposal/create-proposal-form.tsx
  src/components/create-tribe/create-tribe-form-tr.tsx
  src/components/create-tribe/index.tsx
  src/utils/utils.ts
Labels: enhancement

#51 Update Roadmap
  README.md
Labels: documentation

#54 Upgrade Roadmap
  README.md
Labels: documentation

#56 use taproot address as inputs
  next.config.js
  src/components/create-proposal/create-proposal-form.tsx
  src/components/create-tribe/create-tribe-form-tr.tsx
  src/components/nft/select-wallet.tsx
  src/components/ui/author-card.tsx
  src/components/ui/logo-icon.tsx
  src/components/ui/logo.tsx
  src/components/ui/menu-icon.tsx
  src/hooks/useBitpac.ts
  src/layouts/sidebar/_default.tsx
  src/utils/utils.ts
Labels: enhancement, c-priority
